### ISSUE TITLE
Environment failing to validate with "Unexpected error validating environment"

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#639]
# API Services Portal Issue

## User Story

**As a** API Provider,<br>
**I want** to activate an environment<br>
**so that** it appears on the API Directory.

### ENV

- [X] `DEV`
- [X] `TEST`
- [X] `PROD`

### TESTCASE

- Namespace has been assigned to an Organization by the APS team
- Product and Dataset has been created and associated to each other
- A Gateway Service and at least one Route has been created
- Protect a "gateway route" with the `jwt-keycloak` plugin
- Set the Product Environment Authorization field to 'OAuth2 Client Credential Flow'
- Link the corresponding Gateway Service with the Environment
- Check the "Enabled Environment" box

### EXPECTED

- The environment is enabled

### ACTUAL

- Get an error "Unexpected error validating environment"

### ERROR

```
error: [wf.ValidateActiveEnv] Validation threw an exception TypeError: Cannot read properties of undefined (reading 'startsWith')
at /app/dist/services/workflow/validate-active-environment.js:121:153
at /app/dist/services/workflow/validate-active-environment.js:173:17
at Array.filter (<anonymous>)
at /app/dist/services/workflow/validate-active-environment.js:172:64
at Array.filter (<anonymous>)
at /app/dist/services/workflow/validate-active-environment.js:172:32
at Array.filter (<anonymous>)
at /app/dist/services/workflow/validate-active-environment.js:125:44
at Generator.next (<anonymous>)
at fulfilled (/app/dist/services/workflow/validate-active-environment.js:5:58)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
error: [general] GraphQL Error: You attempted to perform an invalid mutation
```

## Notes

The plugin configuration for Gateway Routes are not getting parsed in the same way as the Gateway Service plugins, which results in an unexpected parsing check related to validation of the "well_known_template".

**Comment by ikethecoder** [comment]
Example minimal gateway config:
```
services:
- name: a-service-for-anontest
  host: httpbin.org
  tags: [ ns.anontest ]
  port: 443
  protocol: https
  retries: 0
  routes:
  - name: a-service-for-anontest-route
    tags: [ ns.anontest ]
    hosts:
    - a-service-for-anontest.api.gov.bc.ca
    paths:
    - /
    methods:
    - GET
    strip_path: false
    https_redirect_status_code: 426
    path_handling: v0
    request_buffering: true
    response_buffering: true
    plugins:
    - name: jwt-keycloak
      tags: [ ns.anontest ]
      config:
        allowed_iss: [ "https://auth.service" ]
        well_known_template: "https://auth.service/.well-known/configuration"
```
