### ISSUE TITLE
MongoDB Feature Branch Upgrade Issue

### ISSUE THREAD

**Issue by jTendeck** [bcgov/api-services-portal#668]
It seems the Bitnami Helm Chart repo no longer supports the version of the MongoDB chart used in API Services Portal feature branch deployments (10.31.5). An attempt was made to upgrade to the closest available chart version (12.1.20) but now there are issues with the deployments in OpenShift. It appears the MongoDB container keeps crashing, and the generic-api pods are not able to connect to the MongoDB container. Both pod enter a CrashLoopBackOff cycle.

**Comment by ikethecoder** [comment]
I was able to resolve by updating the chart values to:

```
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 100%
    
readinessProbe:
  timeoutSeconds: 20
  
livenessProbe:
  timeoutSeconds: 20
```

And then having the image tag `5.0-7a639fba` and Chart version `12.1.31`.

The updateStrategy before was `Recreate` and the readinessProbe/livenessProbe need to be increased to 20 secs to avoid issues.
